[font]
size = 11
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[colors.primary]
background = "#0f111a"
foreground = "#e1e2e7"

[colors.normal]
black   = "#1a1b26"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#b9f27c"
yellow  = "#ff9e64"
blue    = "#7aa2f7"
magenta = "#c0a9f7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[window.padding]
x = 12
y = 10

[window]
opacity = 0.93  # 1.0 = fully opaque, lower = more transparent

